# Generated by Django 4.2.1 on 2023-05-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinPlateDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_depth', models.FloatField()),
                ('beam_width', models.FloatField()),
                ('column_depth', models.FloatField()),
                ('column_width', models.FloatField()),
                ('bolt_diameter', models.FloatField()),
                ('bolt_grade', models.CharField(max_length=10)),
                ('weld_thickness', models.FloatField()),
                ('plate_thickness', models.FloatField()),
                ('plate_length', models.FloatField()),
                ('plate_width', models.FloatField()),
                ('axial_force', models.FloatField()),
                ('shear_force', models.FloatField()),
                ('bending_moment', models.FloatField()),
                ('plate_shear_capacity', models.FloatField(blank=True, null=True)),
                ('bolt_shear_capacity', models.FloatField(blank=True, null=True)),
                ('bolt_bearing_capacity', models.FloatField(blank=True, null=True)),
                ('bolt_capacity', models.FloatField(blank=True, null=True)),
                ('plate_bending_capacity', models.FloatField(blank=True, null=True)),
                ('bolt_required', models.IntegerField(blank=True, null=True)),
                ('plate_required', models.IntegerField(blank=True, null=True)),
                ('plate_thickness_provided', models.FloatField(blank=True, null=True)),
                ('plate_length_provided', models.FloatField(blank=True, null=True)),
                ('plate_width_provided', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteelDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinPlateDesignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolt_shear_stress', models.FloatField(blank=True, null=True)),
                ('bolt_bearing_stress', models.FloatField(blank=True, null=True)),
                ('bolt_capacity_check', models.CharField(blank=True, max_length=10, null=True)),
                ('plate_shear_stress', models.FloatField(blank=True, null=True)),
                ('plate_bending_stress', models.FloatField(blank=True, null=True)),
                ('plate_capacity_check', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('fin_plate_design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.finplatedesign')),
            ],
        ),
        migrations.AddField(
            model_name='finplatedesign',
            name='fin_plate_design_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.finplatedesignreport'),
        ),
    ]
